services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      args:
        - RATELIMITS_DB_NAME=ratelimits
        - RATELIMITS_DB_USER=${RATELIMITS_DB_USER}
        - RATELIMITS_DB_PASSWORD=${RATELIMITS_DB_PASSWORD}
        - RATELIMITS_IP_LIMIT=${RATELIMITS_IP_LIMIT}
        - DELAY_MAX=${DELAY_MAX}
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${API_PORT}:8080"
    restart: always
    depends_on:
      - ratelimits-db

  ratelimits-db:
    container_name: ratelimits-db
    build:
      context: ./ratelimits-db
      dockerfile: Dockerfile
      args:
        - RATELIMITS_DB_NAME=ratelimits
        - RATELIMITS_DB_USER=${RATELIMITS_DB_USER}
        - RATELIMITS_DB_PASSWORD=${RATELIMITS_DB_PASSWORD}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${RATELIMITS_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${RATELIMITS_DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ratelimits
    restart: always
    volumes:
      - ./ratelimits-db/data:/data/db

  docs:
    container_name: docs
    build:
      context: ./
      dockerfile: ./docs/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${DOCS_PORT}:3000"
    restart: always
    depends_on:
      - api