services:
  # api:
  #   container_name: api
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${API_PORT}:8080"
  #   environment:
  #     - NODE_ENV=${API_NODE_ENV}
  #   restart: always
  #   depends_on:
  #     - ratelimits-db

  ratelimits-db:
    container_name: ratelimits-db
    build:
      context: ./ratelimits-db
      dockerfile: Dockerfile
      args:
        - RATELIMITS_DB_NAME=ratelimits
        - RATELIMITS_DB_USER=${RATELIMITS_DB_USER}
        - RATELIMITS_DB_PASSWORD=${RATELIMITS_DB_PASSWORD}
    ports:
      - "${RATELIMITS_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${RATELIMITS_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${RATELIMITS_DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ratelimits
    restart: always
    volumes:
      - ./ratelimits-db/data:/data/db