services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    environment:
      - NODE_ENV=${API_NODE_ENV}
    restart: always

  ratelimit-db:
    container_name: ratelimit-db
    build:
      context: ./ratelimit-db
      dockerfile: Dockerfile
    ports:
      - "${RATELIMIT_DB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${RATELIMIT_DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${RATELIMIT_DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${RATELIMIT_DB_NAME}
    restart: always
    volumes:
      - ./ratelimit-db/data:/data/db