services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    environment:
      - NODE_ENV=${API_NODE_ENV}
    restart: always