name: Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Docker Compose
          run: docker compose -f docker-compose-dev.yml up -d

        - name: Sleep
          run: sleep 30

        - name: Setup Bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: 1.1.1

        - name: Sleep
          run: sleep 30
        
        - name: Setup Tests
          run: cd api && rm bun.lockb && bun install

        - name: Run Tests
          run: bun test
          
        - name: Tear down Docker Compose
          run: docker compose -f docker-compose-dev.yml down